random_seed: 20161026
model: 'Language_Pipeline'

batch_size: 32
max_length: 40
hidden_dim: 32
txt_dim:    128
pixel_dim:  32
epochs:     [100]
modes:      ['language']
dropout: 0.7
batch_norm: False
regularizer: 'l1' # l1, l2
non_linearity: 'tanh'
oov: 1

attention_size: 20
rep_dim:    64
rep_dim_y:  4
rotate: True

kernel_size: 5
kernel_size_y: 4

num_ops: 32

training:   '../Data/trainset_v2.json.gz'
evaluation:   '../Data/devset_v2.json.gz'
predict_source: False
